# Nixpacks configuration for Railway deployment
providers = ["node"]

[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmd = "cd server && npm ci"

[phases.build]
cmd = "echo 'No build needed for Railway server'"

[start]
cmd = "cd server && node railway-server.js"