# Nixpacks configuration for Railway deployment
providers = ["node"]

[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmd = "npm ci && cd server && npm ci"

[phases.build]
cmd = "echo 'Skipping build for simple server'"

[start]
cmd = "npm run start:simple"