[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm run start:simple"
healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckRetries = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3003" }