[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm ci && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckRetries = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3001" }