[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'npm ci --only=production'
]

[phases.build]
cmds = [
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'npm start'

[env]
NODE_ENV = 'production'
PORT = '3001'

[healthcheck]
path = '/health'
interval = 30
timeout = 5
start_period = 15
